name: Validate PR title

on:
  pull_request:
    branches: ["*"]
    types:
      - edited
      - opened
      - synchronize

permissions:
  pull-requests: read

jobs:
  check-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
